# Running Standard's rules via RuboCop
# from https://github.com/standardrb/standard
require:
  - standard

plugins:
  - standard-custom
  - standard-performance
  - rubocop-performance

inherit_gem:
  standard: config/base.yml
  standard-custom: config/base.yml
  standard-performance: config/base.yml
