default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: surf_radio_development
  cache:
    <<: *default
    database: surf_radio_development_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: surf_radio_development_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: surf_radio_development_cable
    migrations_paths: db/cable_migrate

test:
  primary:
    <<: *default
    database: surf_radio_test
  cache:
    <<: *default
    database: surf_radio_test_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: surf_radio_test_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: surf_radio_test_cable
    migrations_paths: db/cable_migrate

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *default
    url: <%= ENV.fetch("CACHE_DATABASE_URL") { "#{ENV["DATABASE_URL"]}_cache" } %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    url: <%= ENV.fetch("QUEUE_DATABASE_URL") { "#{ENV["DATABASE_URL"]}_queue" } %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    url: <%= ENV.fetch("CABLE_DATABASE_URL") { "#{ENV["DATABASE_URL"]}_cable" } %>
    migrations_paths: db/cable_migrate
